workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter clean
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
